1Plant Website/Plant Website/Website/routes.py
from flask import Flask, render_template, request, flash, Blueprint, current_app
#Importing Contact Form
from .forms import ContactForm
from flask_mail import Message
from flask_login import current_user
#Importing app and mail instances from __init__.py
from . import mail



bp = Blueprint('contact', __name__)

@bp.route('/contact', methods=['GET','POST'])
def contact():
    form = ContactForm()
    success = False #Initalising success as false
 
    if request.method == 'POST':
        #If the inputs are not valid an error will flash and the page will be reloaded
        if form.validate() == False:
            flash('All fields are required.')
            return render_template('contact.html', form=form, user=current_user)
        #Success message
        else:
            msg = Message(form.subject.data, sender=current_app.config['MAIL_USERNAME'], recipients=['270268490@yoobeestudent.ac.nz','270278266@yoobeestudent.ac.nz', '270045467@yoobeestudent.ac.nz'])
            #Formatting email
            msg.body =f"""
            From: {form.name.data} <{form.email.data}>
            {form.message.data}
            """
            mail.send(msg) #Sending the email
            return render_template('contactSuccess.html', form=form, user=current_user)
    elif request.method == 'GET':
        return render_template('contact.html', form=form, user=current_user)
    
    

1Plant Website/Plant Website/Website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import User, AccountDetails, ShopProducts, UserCart, OrderItem, Order
from .forms import SearchForm, ContactForm
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import Session
from . import db 
import json 
import sqlite3 as sql
import re

views = Blueprint('views',__name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    products = featuredProducts()
    return render_template("home.html", user=current_user, products=products)
 
@views.route('/featuredProducts')
def featuredProducts():
    #Specifying the products displayed by id
    productIds = [5,3,2,4]
 
    #Creating a session
    session = Session(db.engine)
 
    #Database queries
    products = session.query(ShopProducts).filter(ShopProducts.id.in_(productIds)).all()
 
    session.close()
    return products

#Function that handles seraches and returning product lists. Created to be called when needed in order to be DRY.
def getShopProducts():
    form = SearchForm()
    products = []

    if request.method == 'POST':
        
        if form.validate_on_submit():
            search_term = form.search.data
        if not search_term:
            flash('Please enter a search term', category='error')
        else:
            #Separating the search_term into separate words
            search_term = search_term.strip()
            search_words = search_term.split()

            #Query displaying products that match search_words in their name, summary, description or category
            products = ShopProducts.query.filter(
                (ShopProducts.name.contains(search_term)) |
                (ShopProducts.category.contains(search_term)) |
                (ShopProducts.summary.contains(search_term)) |
                db.or_(*[ShopProducts.description.contains(word) for word in search_words])
            ).all()
            if not products:
                flash('No products found', category='error')
    else:
        products = ShopProducts.query.all()
    return form, products

@views.route('/shop', methods=['GET', 'POST'])
def shopProducts():
    
    form, products = getShopProducts()

    return render_template('shop.html', user=current_user, products=products, form=form)

@views.route('/shopPlants', methods=['GET', 'POST'])
def shopProductsPlants():

    form, products = getShopProducts()

    return render_template('shopPlants.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsCactiSucculents', methods=['GET', 'POST'])
def shopPlantsCactiSucculents():

    form, products = getShopProducts()

    return render_template('shopPlantsCactiSucculents.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFlowers', methods=['GET', 'POST'])
def shopPlantsFlowers():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFlowers.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFlowersAnthuriums', methods=['GET', 'POST'])
def shopPlantsFlowersAnthuriums():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFlowersAnthuriums.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFlowersOrchids', methods=['GET', 'POST'])
def shopPlantsFlowersOrchids():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFlowersOrchids.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFlowersOther', methods=['GET', 'POST'])
def shopPlantsFlowersOther():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFlowersOther.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFlowersPeaceLily', methods=['GET', 'POST'])
def shopPlantsFlowersPeaceLily():  

    form, products = getShopProducts()

    return render_template('shopPlantsFlowersPeaceLily.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliage', methods=['GET', 'POST'])
def shopPlantsFoliage():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliage.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliageCalathea', methods=['GET', 'POST'])
def shopPlantsFoliageCalathea():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliageCalathea.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliageCarnivorous', methods=['GET', 'POST'])
def shopPlantsFoliageCarnivorous():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliageCarnivorous.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliageMonstera', methods=['GET', 'POST'])
def shopPlantsFoliageMonstera():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliageMonstera.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliageOther', methods=['GET', 'POST'])
def shopPlantsFoliageOther():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliageOther.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliagePhilodendron', methods=['GET', 'POST'])
def shopPlantsFoliagePhilodendron():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliagePhilodendron.html', user=current_user, products=products, form=form)

@views.route('/shopPlantsFoliageTrailing', methods=['GET', 'POST'])
def shopPlantsFoliageTrailing():

    form, products = getShopProducts()
        
    return render_template('shopPlantsFoliageTrailing.html', user=current_user, products=products, form=form)

@views.route('/shopPotsPlanters', methods=['GET', 'POST'])
def shopProductsPotsPlanters():

    form, products = getShopProducts()
        
    return render_template('shopPotsPlanters.html', user=current_user, products=products, form=form)

@views.route('/shopPotsPlantersPlanters', methods=['GET', 'POST'])
def shopPotsPlantersPlanters():

    form, products = getShopProducts()
        
    return render_template('shopPotsPlantersPlanters.html', user=current_user, products=products, form=form)

@views.route('/shopPotsPlantersPots', methods=['GET', 'POST'])
def shopPotsPlantersPots():

    form, products = getShopProducts()
        
    return render_template('shopPotsPlantersPots.html', user=current_user, products=products, form=form)


@views.route('/shopPlantKits', methods=['GET', 'POST'])
def shopProductsPlantKits():

    form, products = getShopProducts()

    return render_template('shopPlantKits.html', user=current_user, products=products, form=form)

@views.route('/shopGiftCards', methods=['GET', 'POST'])
def shopProductsGiftCards():
    
    form, products = getShopProducts()

    return render_template('shopGiftCards.html', user=current_user, products=products, form=form)

@views.route('/shopSuppliesAccessories', methods=['GET', 'POST'])
def shopProductsSuppliesAccessories():
    
    form, products = getShopProducts()

    return render_template('shopSuppliesAccessories.html', user=current_user, products=products, form=form)

@views.route('/shopSuppliesAccessoriesDecor', methods=['GET', 'POST'])
def shopSuppliesAccessoriesDecor():

    form, products = getShopProducts()
        
    return render_template('shopSuppliesAccessoriesDecor.html', user=current_user, products=products, form=form)

@views.route('/shopSuppliesAccessoriesPlantCare', methods=['GET', 'POST'])
def shopSuppliesAccessoriesPlantCare():

    form, products = getShopProducts()
        
    return render_template('shopSuppliesAccessoriesPlantCare.html', user=current_user, products=products, form=form)

@views.route('/shopSuppliesAccessoriesTools', methods=['GET', 'POST'])
def shopSuppliesAccessoriesTools():

    form, products = getShopProducts()
        
    return render_template('shopSuppliesAccessoriesTools.html', user=current_user, products=products, form=form)

@views.route('/product/<int:id>')
def product(id):

    product = ShopProducts.query.get_or_404(id)

    return render_template('product.html', user=current_user, product=product)

@views.route('/addToCart/<int:productId>', methods=['POST'])
@login_required
def addToCart(productId):
    product = ShopProducts.query.get_or_404(productId)
    existingCartItem = UserCart.query.filter_by(userId=current_user.id, productId=productId).first()

    qty = int(request.form['quantity'])

    if existingCartItem:
        existingCartItem.quantity += qty
        db.session.commit()
        flash('Product quantity updated in cart', category='success')
    else:
        newCartItem = UserCart(userId=current_user.id, productId=productId, quantity=qty)
        db.session.add(newCartItem)
        db.session.commit()
        flash('Product added to cart', category='success')

    return redirect(url_for('views.shopProducts'))

@views.route('/removeFromCart/<int:productId>', methods=['POST'])
@login_required
def removeFromCart(productId):
            
    existingCartItem = UserCart.query.filter_by(userId=current_user.id, productId=productId).first()

    if existingCartItem:
        if existingCartItem.quantity > 1:
            existingCartItem.quantity -= 1
            db.session.commit()
            flash('One of these removed from cart', category='success')
        else:
            db.session.delete(existingCartItem)
            db.session.commit()
            flash('Product removed from cart', category='success')
    else:
            flash('Product not found in cart', category='error')

    return redirect(url_for('views.viewCart'))

 
@views.route('/viewCart', methods=['GET'])
@login_required
def viewCart(): 

    cartItems = UserCart.query.filter_by(userId=current_user.id).all()

1Plant Website/Plant Website/Website/templates/aboutUs.html
<!--Inherits from navBase and overrides blocks-->
{% extends "navBase.html" %}
{% block title %}aboutUs{% endblock %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %} 
{% if messages %}
    <ul>
        {% for category, message in messages %}
            <li class="{{category}}"> {{message}} </li>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/aboutUs.css') }}">


<div class="aboutUs">
    <h1>About Us</h1>
    <div class="aboutUsContent">
        <p>
            Welcome to Roots, your one-stop destination for plants, pots, and planting equipment. We believe that nurturing plants enhances the beauty of your space and brings tranquility and joy to your life.
            
            Our mission is to inspire and support plant enthusiasts of all levels, making gardening accessible and enjoyable for everyone. <br> <br>
            
            We offer a diverse selection of high-quality indoor and outdoor plants, stylish and functional pots, and essential planting tools. Each product is carefully chosen to ensure you bring home a thriving green companion.
            
            Roots was founded by a group of passionate plant lovers who wanted to share their love for greenery with the world. <br> <br>
            
            Our journey is rooted in the belief that everyone deserves to enjoy the benefits of having plants in their lives. We take pride in offering only the best products and expert advice, ensuring your gardening success.
            
            Join us at Roots and discover the joy of growing and nurturing plants. Let’s create greener, more beautiful spaces together!
        </p>
        <div class="aboutUsIMG">
            <img height="500px" src="{{ url_for('static', filename='aboutUsPhoto.jpg')  }}">
            <p>Roots store in full bloom</p>
        </div>    
    </div>
</div>

{% endblock %}

1Plant Website/Plant Website/Website/templates/accountDetails.html
{% extends "navBase.html" %}
{% block title %} Account Details {% endblock %}
{% block content %}
        {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %}
            <ul class="message">
                {% for category, message in messages %}
                    <li class="{{category}}"> {{message}} </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/accountDetails.css') }}">

        <h3 class="myAccountHeading" align="center" >My Account</h3>

        <div class="detailsMain">

            <div class="detailsGroupBody">

                <h1>Personal Details</h1>

                <div class="detailsGroup">
                    <p class="detailsFlexLabel">Name:</p>
                    {% if accountDetails.lastName == None or accountDetails.lastName == "None" or accountDetails.lastName == "" %}    
                    <h2>{{ accountDetails.firstName }} </h2>
                    {% else %}
                    <h2>{{ accountDetails.firstName }} {{ accountDetails.lastName }}</h2>
                    {% endif %}
                </div>

                <div class="detailsGroup">
                    <p class="detailsFlexLabel">Email Address:</p>
                    <h2>{{ accountDetails.email }} </h2>
                </div>

                <div class="detailsGroup">
                    <p class="detailsFlexLabel">Mobile:</p>
                    {% if accountDetails.mobileNo == None %}
                    <h2> - </h2>      
                    {% else %}
                    <h2>{{ accountDetails.mobileNo }} </h2>
                    {% endif %}
                </div>

            </div>


            <div class="detailsGroupBody">

                <h1>Shipping and Payment Details</h1>

                <div class="shipPayGroup">
                    <p class="detailsFlexLabel">Shipping Address:</p>
                    {% if accountDetails.addressHouseNo == None or accountDetails.addressHouseNo == "" %}
                    <h2> - </h2>  
                    {% else %}
                    <h2>{{ accountDetails.addressHouseNo }} {{accountDetails.addressStreetName }}, {{accountDetails.addressSuburb }}, {{accountDetails.addressCity }} {{accountDetails.addressPostCode }}</h2>
                    {% endif %}
                </div>


                <div class="shipPayGroup">
                    <p class="detailsFlexLabel">Payment Details:</p>
                    {% if accountDetails.paymentCardNo == None or accountDetails.paymentCardNo == "" %}
                    <h2> - </h2>     
                    {% else %}
                    <h2>Visa Debit </h2>
                    <h2>{{ maskedCard }}</h2>
                    <h2>Exp: {{accountDetails.paymentCardExp }}</h2>
                    {% endif %}
                </div>

            </div>
            
        </div>

       

        <button type="button" align="center" class="editButton" id="editAccountDetails"><a href="/editAccountDetails">Edit</a></button>
       
{% endblock %} 

1Plant Website/Plant Website/Website/templates/home.html
<!--Inherits from navBase and overrides blocks-->
{% extends "navBase.html" %}
{% block title %}Home{% endblock %}

{% block imgblok %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
<div class="paraOne"> 
    <h1 class="paraOneTitle">Give the gift of life</h1>
    <p class="paraOneText">Buy a plant kit today</p>
    <a class="paraOneButton" href="/shop">Shop Now</a>

</div>
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %} 
{% if messages %}
    <ul class="message">
        {% for category, message in messages %}
            <li class="{{category}}"> {{message}} </li>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">

<div class="whoAreWe">
    <h1>Who are we?</h1>
    <p>Here at Roots, located in the heart of Auckland, New Zealand, we pride ourselves on being more than just a plant and pot company, we're cultivators of dreams and nurturers of growth.<br><br>

        As a small business, quality assurance is at the forefront of everything we do. From the vibrant foliage of our plants to the artisanal craftsmanship of our pots, we hand-select each item with meticulous care, ensuring that only the finest specimens grace our shelves.<br><br>
        
        But our commitment to excellence doesn't stop there. Sustainability is woven into the fabric of our ethos, guiding every decision we make. From eco-friendly practices to community engagement, we strive to leave a positive impact on our environment and our community.<br><br>
        
        More than just a business, Roots is a gathering place for plant enthusiasts and dreamers alike. With our warm and welcoming storefront, we invite you to immerse yourself in a world of greenery and creativity. Whether you're attending one of our workshops or simply browsing our curated collection, you're sure to find inspiration and connection here.<br><br>
        
        As we continue to grow, we remain rooted in our values to quality, sustainability, and community. With every leaf that unfurls and every dream that takes root, Roots stands as a testament to the power of nature and the boundless potential of small businesses with big hearts.</p>
</div>


<div class="featuredProducts">
    <h1>Featured Products</h1>
    <div class="products">
 
        {% for product in products %}
 
        <div class="productItem">
            <a href = "/product/{{product.id}}">
                <img src="{{ url_for('static', filename='img/' + product.imageUrl) }}" width="200" alt="Plant image">
                <h4>{{ product.name }}</h4>
                <p>{{ product.summary }}</p>
                <p>$ {{ product.price }}</p>
            </a>
        </div>
        {% endfor %}
 
    </div>
</div>
{% endblock %}

1Plant Website/Plant Website/Website/templates/navBase.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name ="viewport" content="width-device-width, initial-scale=1"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/navBase.css') }}">
        <link rel="stylesheet" href="https://use.typekit.net/btr0hfq.css">

        <!--creating a block template that children will be able to override-->
        <title>{% block title %}Nav Base{% endblock %}</title>
    </head>

    <body>
        <nav class="navBar">

            <div class="navBarMain">
                    
                <!--Icon Logo-->
                <a class="navBarLogoIcon" href="/"> <!--linking to the home page-->
                    <img height="150px" src="{{ url_for('static', filename='iconLogo.png') }}">
                </a>

                <!--Typographic Logo-->
                <a class="navBarLogoType" href="/"><!--need to link to page-->
                    <img height="110px" src="{{ url_for('static', filename='typographicLogo.png') }}">
                </a>

        
                
                <div class="navBarCategories"> 
                    <!--Nav items-->
                    <a class="navItem" id="shop" href="/shop">Shop</a>
                    <a class="navItem" id="aboutUs" href="/aboutUs">About Us</a>
                    <a class="navItem" id="contact" href="{{ url_for('contact.contact')}}">Contact</a>
                </div>

                
                {% if user.is_authenticated %} 
                <!--Nav icons-->
                <div class="loggedSection">
                    <a class="loggedLinks" id="logout" href="/logout">Logout</a>  
                    
                    <a class="loggedIcons" href="/viewCart"><!--need to link to cart page-->
                        <img height="40px" src="{{ url_for('static', filename='shoppingCart.png')  }}">
                    </a>

                    <a class="loggedIcons" href="/accountDetails">
                        <img height="40px" src="{{ url_for('static', filename='accountIcon.png') }}">
                    </a>
                    
                </div>
                {% else %}
                <div class="loginSection">
                    <a class="loginLinks" id="login" href="/login">Login</a> 
                    <a class="loginLinks" id="signUp" href="/signUp">Sign up</a> 
                </div>
                {% endif %}

            </div>      
        </nav>




        <div class="iamgeblok">
            {% block imgblok %}
            {% endblock %}
        </div>
                

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>



        
        <footer class="footer">
            <div class="footerMain"> 

                <div class="column1">
                    <a class="column1Text" href="{{ url_for('contact.contact')}}"><h5>Contact</h5></a>
                    <a class="column1Text" href="/aboutUs"><h5>About Us</h5></a>

                    
                    <ul class="socialMedias"> 
                        <li class="socialMediaItems"> 
                            <a href="/shop"><img height="40px" src="{{ url_for('static', filename='facebookIcon.png') }}"></a>
                        </li> 

                        <li class="socialMediaItems" href="#"> 
                            <a href="/shop"><img height="40px" src="{{ url_for('static', filename='twitterIcon.png') }}"></a>
                        </li> 

                        <li class="socialMediaItems" href="#"> 
                            <a href="/shop"><img height="40px" src="{{ url_for('static', filename='instaIcon.png') }}"></a> 
                        </li> 
                    </ul> 
                </div> 

                       
                <a class="footerLogo" href="/"> <!--linking to the home page-->
                    <img height="150px" src="{{ url_for('static', filename='iconLogo.png') }}">
                </a>    

                <div class="openHours"> 
                    <h5 class="openHoursTitle">Open Hours</h5> 
                    <ul class="openHoursList"> 
                        <li>Weekdays 10:00 - 5:00</li> 
                        <li>Saturday 11:00 - 4:30</li> 
                        <li>Sunday 11:00 - 3:30</li> 
                    </ul> 
                </div> 
            </div> 
        </footer> 

    </body>
</html>

1Plant Website/Plant Website/Website/templates/product.html
<!--Inherits from navBase and overrides blocks-->
{% extends "navBase.html" %}
{% block title %}{{ product.name }}{% endblock %}
 
 
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/product.css') }}">





    <!-- insert breadcrumb nav here ? -->

    <div class="breadcrumbNav" align="center">
        {% if product.subSubCategory != "None" and product.subSubCategory != None %}
        <a href="/shop">Shop</a> > <a href="/shop{{product.category}}">{{product.category}}</a> > <a href="/shop{{product.category}}{{product.subCategory}}">{{product.subCategory}}</a> > <a href="/shop{{product.category}}{{product.subCategory}}{{product.subSubCategory}}">{{product.subSubCategory}}</a> > {{product.name}}
        {% elif product.subCategory != "None" and product.subCategory != None %}
        <a href="/shop">Shop</a> > <a href="/shop{{product.category}}">{{product.category}}</a> > <a href="/shop{{product.category}}{{product.subCategory}}">{{product.subCategory}}</a> > {{product.name}}
        {% else %}
        <a href="/shop">Shop</a> > <a href="/shop{{product.category}}">{{product.category}}</a> > {{product.name}}
        {% endif %}
    </div>





    <div class="flexBox">

        <div class="productImage">
            <img src="{{ url_for('static', filename='img/' + product.imageUrl) }}" width="400" alt="Plant image">
        </div>

        <div class="infoFlex">

            <div class="productInfo">

                <div class="productName">
                    {{ product.name }}
                </div>


                <div class="productSummary">
                    {% if product.summary == "None" or product.summary == None %} 
                    
                    {% else %} 

                    {{ product.summary }}

                    {% endif %}
                </div>
                
                
                <div class=productPrice> 
                    ${{ product.price }} 
                </div>


            </div>

            <div class="productCart">
                <p> Click and Collect available</p>
                <p> Delivery available</p>

                <div class="qtyAndBtn">

                    <div class="quantity">
                        <select name="quantity" id="qty">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            
                        </select>
                    </div>
                
                    <form action="{{ url_for('views.addToCart', productId=product.id) }}" method="POST">
                        <input type="hidden" name="quantity" id="qtySelect">
                        <button class="addBtn" type="submit" onclick="updateQty()">
                            Add to Cart
                        </button>
                    </form>
                </div>

            


            </div>
        </div>

    </div>

    <div class="description">
        <h1>Description</h1>
        <p>{{ product.description }}</p>
    </div>

    <script>
        function updateQty() {
            var qtySelect = document.getElementById('qty').value;
            document.getElementById('qtySelect').value = qtySelect;
        }
    </script>


{% endblock %}

1Plant Website/Plant Website/Website/templates/viewCart.html
{% extends "navBase.html" %}
{% block title %}Cart{% endblock %}
{% block content %}

<div class=pageHeader>
    <h1>Your Cart</h1>
</div>


<link rel="stylesheet" href="{{ url_for('static', filename='css/viewCart.css') }}">



    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="message">
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% if cartItems %}
        <div class="cart">   
            {% for item in cartItems %}
            <div class="cartItemContain">
                <div class="cartItem">
                    <div class="btnFlex">
                    <form id="deleteOne" action="{{ url_for('views.removeFromCart', productId=item.productId) }}" method="POST">
                        <button class="delBtn"><img class="binImage" height="40px" src="{{ url_for('static', filename='trashIcon.png') }}"></button>
                    </form>
                    </div>

                    <div class="productImage">
                        <img src="{{ url_for('static', filename='img/' + item.shopproduct.imageUrl) }}" width="200" height="150" alt="Plant image">
                    </div>

                    <div class="itemTitle">
                        <h2 class="subHead">{{ item.shopproduct.name }}</h2>
                        {% if item.shopproduct.summary %}
                        {{item.shopproduct.summary}}
                        {% else %}
                        <p>-</p>
                        {% endif %}
                    </div>

                    <div class="qtyFlex">
                    <div class="qty"> {{ item.quantity }} </div>
                    </div>
                    <div class="priceFlex">
                    <div class="price"><b>${{ item.shopproduct.price * item.quantity }}</b></div>
                    </div>

                </div>
            </div>
                
            {% endfor %}
        
        </div>

        
        <div class="cartSummaryContainer">
            <div class="cartSummaryItems">
                <p>{{ totalQuantity }} items</p>
                <p>Shipping: </p>
                <p><b>Total:</b> </p>
            </div>
            
            <div class="cartSummaryItems2">
                <p>${{ totalPrice }}</p>
                <p><i>Free</i> </p>
                <p><b>${{ totalPrice }}</b></p>
            </div>
        </div>


        
        <form class="checkoutBtnLink" action="{{ url_for('views.checkout') }}">
            <button class="checkoutBtn">Go to Checkout</button>
        </form>

    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}

    {% endblock %}